before_script:
  - bash .gitlab-ci.sh

stages:
  - test

# Services
services:
  - mysql:latest

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql

# Speed up builds
cache:
  key: $CI_BUILD_REF_NAME
  paths:
    - vendor
    - node_modules
    - public
    - ~/.composer/cache/files
    - ~/.yarn-cache

test:
  stage: test
  services:
    - mysql:5.7

  image: chilio/laravel-dusk-ci:stable

  script:
    
    - yarn --network-concurrency 1
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - bower update --allow-root --quiet
    - npm run dev
    - configure-laravel
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors --stderr
    - start-nginx-ci-project
    - php artisan dusk --colors --debug

  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 1 days
    when: always